<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project Configuration -->

  <PropertyGroup>
    <Description>PowerShell interface for PRTG Network Monitor</Description>
    <TargetFramework Condition="'$(TargetFramework)' == ''">netstandard2.0</TargetFramework>
    <OutputPath>bin\$(Configuration)\$(TargetFramework)\PrtgAPI\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)\$(Configuration)\$(TargetFramework.ToLowerInvariant())\</IntermediateOutputPath>
    <IsPackable>false</IsPackable>
    <LangVersion>13.0</LangVersion>
    <AssemblyName>PrtgAPI.PowerShell</AssemblyName>
    <RootNamespace>PrtgAPI.PowerShell</RootNamespace>
    <AssemblyTitle>PowerShell interface for PRTG Network Monitor</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>PrtgAPI.Tests.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- Common Definitions -->

  <Import Project="..\..\build\Common.props" />

  <PropertyGroup>
    <DocumentationFile>$(OutputPath)PrtgAPI.PowerShell.xml</DocumentationFile>
  </PropertyGroup>

  <!-- References -->
  <!-- For PackageReference versions please see Directory.Packages.props -->

  <ItemGroup>
    <ProjectReference Include="..\PrtgAPI\PrtgAPI.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(EnableSourceLink)' == 'true'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" />
  </ItemGroup>

  <!-- Build -->

  <ItemGroup>
    <PowerShellResources Include="PowerShell\Resources\*.*" />
    <PowerShellFunctions Include="PowerShell\Functions\*.*" />
  </ItemGroup>

  <!-- Target is executed twice for netcoreapp when pluralized TargetFrameworks is specified -->
  <Target Name="Resources" AfterTargets="Build" Condition="'$(TargetDir)' != ''">
    <Message Importance="high" Text="Copying resources" />
    <Copy SourceFiles="@(PowerShellResources)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PowerShellFunctions)" DestinationFolder="$(OutputPath)Functions" SkipUnchangedFiles="true" />
  </Target>
</Project>