<Project>
  <Import Project="build\Version.props" />

  <PropertyGroup>
    <!-- Project-->

    <!-- Put project.assets.json files in per-configuration folder so we can change target frameworks
         when switching between configurations -->
    <MSBuildProjectExtensionsPath>obj\$(Configuration)\</MSBuildProjectExtensionsPath>

    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>

    <Copyright>(c) 2015 lordmilko. All rights reserved.</Copyright>

    <!-- Configuration -->

    <IsDebug Condition="'$(Configuration)' == 'Debug'">true</IsDebug>
    <IsDebug Condition="'$(IsDebug)' == ''">false</IsDebug>

    <IsRelease Condition="'$(Configuration)' == 'Release'">true</IsRelease>
    <IsRelease Condition="'$(IsRelease)' == ''">false</IsRelease>

    <!-- Operating System-->

    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsWindows Condition="'$(IsWindows)' == ''">false</IsWindows>

    <IsUnix Condition="'$(IsWindows)' == 'false'">true</IsUnix>
    <IsUnix Condition="'$(IsUnix)' == ''">false</IsUnix>

    <DefineConstants Condition="$(IsWindows)">$(DefineConstants);WINDOWS</DefineConstants>
    <DefineConstants Condition="$(IsUnix)">$(DefineConstants);UNIX</DefineConstants>

    <!-- Target Framework Conditions -->

    <BuildAllTargets Condition="$(IsDebug)">false</BuildAllTargets>

    <BuildAllTargets Condition="$(IsRelease) OR '$(BuildAllTargets)' == 'true'">true</BuildAllTargets>
    <BuildAllTargets Condition="'$(BuildAllTargets)' != 'true'">false</BuildAllTargets>



    <!-- Target frameworks are defined per project file. -->
  </PropertyGroup>
  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>
</Project>