<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project Configuration -->

  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>PrtgAPI.Tests.IntegrationTests</AssemblyName>
    <RootNamespace>PrtgAPI.Tests.IntegrationTests</RootNamespace>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <Import Project="..\..\build\Common.props" />

  <!-- Content -->

  <ItemGroup>
    <Compile Include="..\PrtgAPI\Enums\Serialization\ObjectPropertyCategory.cs" Link="Support\ObjectPropertyCategory.cs" />

    <None Include="..\..\Build\CI\Tests\Appveyor.Tests.ps1" Link="PowerShell\Infrastructure\Appveyor.Tests.ps1" />
    <None Include="..\..\Build\CI\Tests\CI.Tests.ps1" Link="PowerShell\Infrastructure\CI.Tests.ps1" />
    <None Include="..\..\Build\CI\Tests\Travis.Tests.ps1" Link="PowerShell\Infrastructure\Travis.Tests.ps1" />
  </ItemGroup>

  <!-- References -->
  <!-- For PackageReference versions please see Directory.Packages.props -->

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup Condition="'$(FrameworkType)' == 'Core'">
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrtgAPI.Tests.UnitTests\PrtgAPIv17.Tests.UnitTests.csproj" />
    <ProjectReference Include="..\PrtgAPI\PrtgAPIv17.csproj" />
  </ItemGroup>
</Project>
